name: 直播源自动更新
on:
  push:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install requests

      - name: 运行更新脚本
        run: python3 update.py

      - name: 强制提交
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "每日0点自动更新" --allow-empty || echo "无变化，跳过"
          git push
